### ISSUE TITLE
Creating the canvas

### ISSUE THREAD

**Issue by Gunes315** [hpi-swa-teaching/PixelEditor#1]
As a painter I want to create a canvas in order to draw my pixel art

- [x]  create a grid, in which every cell can be colored
- [x] ask users for width and height when creating a new canvas

**Comment by lisaaaa11** [comment]
Missing UI, size of canvas still adjusted as magic number, and very large pixels saved as magic number, problem will be solved, when UI is created!

**Comment by giantheinventor** [comment]
nicht fertig
