### ISSUE TITLE
Opening PixelEditor

### ISSUE THREAD

**Issue by matveysiva** [hpi-swa-teaching/PixelEditor#13]
As a User I want to be able to open Pixel Editor through the Apps Toolbar in squeak in order to access it quickly.

- [x] There has to be a button under "App" whith which you can open the Pixel Editor

**Comment by GHOS939** [comment]
registering needs to be done "by-hand" in every new squeak image
this can't be changed as far as we know --> discuss with customer to approve

**Comment by ekrebs5** [comment]
This won't help for users downloading your project via git, but the two mainways to things like installation etc for people outside your team are the following:
- You create a so called baseline for your project. The baseline can define stuff like dependencies, but also supports a _#postload_ method that is executed after all classes are loaded. This is the way SwaLint is added to your SWT images, we just load the baseline (https://github.com/hpi-swa-teaching/SwaLint)
- You can register it in the _#initialize_ method of one of your classes: When the class is first added to the system, your app is registered (this version might be git-loading compatible).
- If you mainly want to share your project via sar files, similar to the _preamble_ in the example script you can also add a _postscript_ that is executed after all files from the sar are loaded.

To give your project to swa students, the first two versions would be preferred, sar loading would be difficult :)
