### ISSUE TITLE
Choosing colors

### ISSUE THREAD

**Issue by Gunes315** [hpi-swa-teaching/PixelEditor#3]
As a painter I want to choose from an array of different colors in order to express my artistic genius

- [x] with left mouse click on a tile, this color gets changed to the color currently in use
- [x] User Interface with 8 different tiles
- [x] Color of the tiles has to be interchangeable 
- [x] Every color has to be possible

**Comment by giantheinventor** [comment]
- [x] Redo with color picker
- [ ] Implement Singleton 
- [ ] Catch nil values
